/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    CreateInvoiceModal: typeof import('./src/components/CreateInvoiceModal.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FormInput: typeof import('./src/components/common/FormInput.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InvoiceItemsList: typeof import('./src/components/InvoiceItemsList.vue')['default']
    InvoiceList: typeof import('./src/components/InvoiceList.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    LogoComponent: typeof import('./src/components/LogoComponent.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
  }
}
